package KION;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;

import java.time.Duration;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.AfterSuite;
import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;

public class StoreFronSmoke {
	WebDriver driver;

	@Test(priority = 1)
	public void login() throws InterruptedException {
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
		WebElement Login_Link = wait.until(presenceOfElementLocated(By.className("icon-heart")));
		Login_Link.click();
		Thread.sleep(2000);
		WebElement email = driver.findElement(By.xpath("//input[@placeholder='Emailaddress']"));
		email.sendKeys("mar.ig10test@gmail.com");
		Thread.sleep(2000);
		WebElement password = driver.findElement(By.xpath("//input[@placeholder='Password']"));
		password.sendKeys("Test@123");
		Thread.sleep(2000);
		WebElement loginButton = driver.findElement(By.xpath("//button[.='Login']"));
		loginButton.click();
		Thread.sleep(2000);
		WebElement Dealer_Selection = driver
				.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[2]/div[3]/div[1]"));
		Dealer_Selection.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1800)", "driver");
		Thread.sleep(2000);
		Actions action = new Actions(driver);
		WebElement element = driver.findElement(By.xpath("//span[.='L0009408039']"));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement click_WorkSheet = driver.findElement(By.xpath(
				"//button[@data-expresscart-action='https://tst.lindelink.com/INTERSHOP/web/WFS/Linde-Business-Site/en_US/-/USD/ViewCart-AddProductToWorkSheet?ProductSKU=L0009408039&ProductId=L0009408039']"));
		click_WorkSheet.click();
		Thread.sleep(5000);
	}

	@Test(priority = 2, dependsOnMethods = "login", enabled = false)
	public void CLP_PLP() throws InterruptedException, NoSuchElementException {
		WebElement CLP = driver.findElement(By.xpath("//a[.='Linde']"));
		CLP.click();
		Thread.sleep(2000);
		WebElement Sub_CLP = driver.findElement(By.xpath("//h3[.='Maintenance']"));
		Sub_CLP.click();
		Thread.sleep(2000);
		WebElement PLP = driver.findElement(By.xpath("//h3[.='Kits']"));
		PLP.click();
		Thread.sleep(2000);
		Actions action = new Actions(driver);
		WebElement element = driver.findElement(By.xpath("//span[.='3550086503']"));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement click_WorkSheet = driver.findElement(By.xpath(
				"//button[@data-expresscart-action='https://tst.lindelink.com/INTERSHOP/web/WFS/Linde-Business-Site/en_US/-/USD/ViewCart-AddProductToWorkSheet?ProductSKU=3550086503&ProductId=3550086503']"));
		click_WorkSheet.click();
	}

	@Test(priority = 3, dependsOnMethods = "CLP_PLP", enabled = false)
	public void PDP() throws InterruptedException {
		WebElement PDP = driver
				.findElement(By.xpath("//a[@href='https://tst.lindelink.com/p/3550086507']/div/span/img"));
		PDP.click();
		Thread.sleep(2000);
		WebElement Add_to_WorkSheet = driver.findElement(By.xpath("//button[@name='addProductToWorkSheet'][1]"));
		Add_to_WorkSheet.click();
	}

	@Test(priority = 4, dependsOnMethods = "PDP", enabled = false)
	public void Compare() throws InterruptedException {
		WebElement CLP = driver.findElement(By.xpath("//a[.='Linde']"));
		CLP.click();
		Thread.sleep(2000);
		WebElement Sub_CLP = driver.findElement(By.xpath("//h3[.='Maintenance']"));
		Sub_CLP.click();
		Thread.sleep(2000);
		WebElement PLP = driver.findElement(By.xpath("//h3[.='Kits']"));
		PLP.click();
		Thread.sleep(2000);
		WebElement PDP = driver.findElement(By.xpath(
				"//a[@href='https://tst.lindelink.com/p/3550086511']/span[.=\"maintenance package '5000h-H280-H320\"]"));
		PDP.click();
		Thread.sleep(2000);
		WebElement compareIconClick = driver.findElement(By.xpath("//a[@title='Compare']"));
		compareIconClick.click();
		Thread.sleep(2000);
		WebElement Add_to_WorkSheet = driver.findElement(By.xpath("//div[@class='add-to-cart']"));
		Add_to_WorkSheet.click();
		Thread.sleep(2000);
		WebElement minicart_Close = driver.findElement(By.xpath("//a[@href='#miniCart']/span[.='Close']"));
		minicart_Close.click();

	}

	@Test(priority = 5, enabled = false)
	public void OrderTemplate() throws InterruptedException {
		WebElement CLP = driver.findElement(By.xpath("//a[.='Linde']"));
		CLP.click();
		Thread.sleep(2000);
		WebElement Sub_CLP = driver.findElement(By.xpath("//h3[.='Maintenance']"));
		Sub_CLP.click();
		Thread.sleep(2000);
		WebElement PLP = driver.findElement(By.xpath("//h3[.='Kits']"));
		PLP.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(2000);
		WebElement PDP = driver.findElement(
				By.xpath("//div[@class='product-tile-desc']/a[@href='https://tst.lindelink.com/p/3550086513']"));
		PDP.click();
		Thread.sleep(2000);
		WebElement OrderTemplate = driver
				.findElement(By.xpath("//div[@class='pdp-btns']//button[@name='addToWishlistProduct']"));
		OrderTemplate.click();
		Thread.sleep(2000);
		if (driver.findElement(By.name("AddWishlistItem")).isDisplayed()) {
			driver.findElement(By.name("AddWishlistItem")).click();
		} else {
			driver.findElement(By.id("NewWishlistRadioButton")).click();
		}
		Thread.sleep(2000);
		WebElement confirmOK = driver.findElement(By.xpath("//a[.='OK']"));
		confirmOK.click();
		Thread.sleep(2000);
		WebElement OrderTemplatePage = driver.findElement(By.className("icon-heart"));
		OrderTemplatePage.click();
		Thread.sleep(2000);
		WebElement AddtoWorksheet = driver.findElement(By.xpath("//a[@title='Add to Cart']"));
		AddtoWorksheet.click();

	}

	@Test(priority = 6, enabled = false, dependsOnMethods = "login")
	public void Search() throws InterruptedException {
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(3000);
		WebElement searchIcon = driver.findElement(By.xpath("//a[@href='#header-searchbox']"));
		searchIcon.click();
		WebElement searchKeyword = driver.findElement(By.xpath("//*[@id=\"header-searchbox\"]/form/input[1]"));
		searchKeyword.sendKeys("123224");
		Thread.sleep(2000);
		WebElement searchIconClick = driver
				.findElement(By.xpath("/html/body/header/div/div[2]/div[3]/div/div[2]/div/form/button/span/i"));
		searchIconClick.click();
		Thread.sleep(2000);
		WebElement Add_to_WorkSheet = driver.findElement(By.xpath("//button[@name='addProductToWorkSheet'][1]"));
		Add_to_WorkSheet.click();
	}

	@Test(priority = 7, enabled = false, dependsOnMethods = "login")
	public void EmergencyOrder() throws InterruptedException {
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(2000);
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(3000);
		WebElement submitButton = driver.findElement(By.xpath("//div[@class='quick-addbtn']/button[.='Submit']"));
		submitButton.click();
		Thread.sleep(2000);
		WebElement scanEle = new WebDriverWait(driver, Duration.ofSeconds(20))
				.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[3]/div/div/div[2]/button")));
		Actions action = new Actions(driver);
		action.moveToElement(scanEle).click().build().perform();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(3000);
		WebElement ProceedCheckout = driver.findElement(By.xpath("//button[.='Proceed To Checkout']"));
		ProceedCheckout.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		WebElement poNumber = driver.findElement(By.name("PrimaryPO"));
		poNumber.sendKeys("Test_Po 6783");
		Thread.sleep(2000);
		WebElement checkBox_Check = driver.findElement(By.id("terms-conditions-agree"));
		checkBox_Check.click();
		Thread.sleep(2000);
		WebElement Proceed = driver.findElement(By.id("submit-order"));
		Proceed.click();

	}

	@Test(priority = 8, enabled = false, dependsOnMethods = "login")
	public void StockOrder() throws InterruptedException {
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(2000);
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		WebElement OrderType = driver.findElement(By.id("qcOrderType"));
		OrderType.click();
		Thread.sleep(2000);
		WebElement stockOrder = driver.findElement(By.xpath("//option[.='Stock Order']"));
		stockOrder.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(2000);
		WebElement submitButton = driver.findElement(By.xpath("//div[@class='quick-addbtn']/button[.='Submit']"));
		submitButton.click();
		Thread.sleep(2000);
		WebElement scanEle = new WebDriverWait(driver, Duration.ofSeconds(10))
				.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[3]/div/div/div[2]/button")));
		Actions action = new Actions(driver);
		action.moveToElement(scanEle).click().build().perform();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(2000);
		WebElement ProceedCheckout = driver.findElement(By.xpath("//button[.='Proceed To Checkout']"));
		ProceedCheckout.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		WebElement poNumber = driver.findElement(By.name("PrimaryPO"));
		poNumber.sendKeys("Test_Po 6783");
		Thread.sleep(2000);
		WebElement checkBox_Check = driver.findElement(By.id("terms-conditions-agree"));
		checkBox_Check.click();
		Thread.sleep(2000);
		WebElement Proceed = driver.findElement(By.id("submit-order"));
		Proceed.click();
	}

	@Test(priority = 9, enabled = false, dependsOnMethods = "login")
	public void Saved_EmergencyOrder() throws InterruptedException {
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(2000);
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(3000);
		WebElement saveButton = driver.findElement(By.xpath("//button[.='Save Worksheet']"));
		saveButton.click();
		Thread.sleep(2000);
		WebElement workSheetName = driver.findElement(By.xpath("//input[@name='WishlistPropertiesForm_WishlistName']"));
		workSheetName.sendKeys("Emergency Saved Worksheet");
		Thread.sleep(2000);
		WebElement saveChangesButton = driver
				.findElement(By.xpath("//button[@name='EditQuickOrderWishlistProperties']"));
		saveChangesButton.click();
		Thread.sleep(2000);
		WebElement OK_BUTTON = driver.findElement(By.xpath("//a[.='OK']"));
		OK_BUTTON.click();
		Thread.sleep(2000);
		WebElement submitButton = driver.findElement(By.xpath("//div[@class='quick-addbtn']/button[.='Submit']"));
		submitButton.click();
		Thread.sleep(2000);
		WebElement scanEle = new WebDriverWait(driver, Duration.ofSeconds(10))
				.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[3]/div/div/div[2]/button")));
		Actions action = new Actions(driver);
		action.moveToElement(scanEle).click().build().perform();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(3000);
		WebElement ProceedCheckout = driver.findElement(By.xpath("//button[.='Proceed To Checkout']"));
		ProceedCheckout.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		WebElement poNumber = driver.findElement(By.name("PrimaryPO"));
		poNumber.sendKeys("Test_Po 6783");
		Thread.sleep(2000);
		WebElement checkBox_Check = driver.findElement(By.id("terms-conditions-agree"));
		checkBox_Check.click();
		Thread.sleep(2000);
		WebElement Proceed = driver.findElement(By.id("submit-order"));
		Proceed.click();
	}

	@Test(priority = 10, enabled = false, dependsOnMethods = "login")
	public void Saved_StockOrder() throws InterruptedException {
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(2000);
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		WebElement OrderType = driver.findElement(By.id("qcOrderType"));
		OrderType.click();
		Thread.sleep(2000);
		WebElement stockOrder = driver.findElement(By.xpath("//option[.='Stock Order']"));
		stockOrder.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(3000);
		WebElement saveButton = driver.findElement(By.xpath("//button[.='Save Worksheet']"));
		saveButton.click();
		Thread.sleep(2000);
		WebElement workSheetName = driver.findElement(By.xpath("//input[@name='WishlistPropertiesForm_WishlistName']"));
		workSheetName.sendKeys("Stock Saved Worksheet");
		Thread.sleep(2000);
		WebElement saveChangesButton = driver
				.findElement(By.xpath("//button[@name='EditQuickOrderWishlistProperties']"));
		saveChangesButton.click();
		Thread.sleep(2000);
		WebElement OK_BUTTON = driver.findElement(By.xpath("//a[.='OK']"));
		OK_BUTTON.click();
		Thread.sleep(2000);
		WebElement submitButton = driver.findElement(By.xpath("//div[@class='quick-addbtn']/button[.='Submit']"));
		submitButton.click();
		Thread.sleep(2000);
		WebElement scanEle = new WebDriverWait(driver, Duration.ofSeconds(10))
				.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[3]/div/div/div[2]/button")));
		Actions action = new Actions(driver);
		action.moveToElement(scanEle).click().build().perform();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(2000);
		WebElement ProceedCheckout = driver.findElement(By.xpath("//button[.='Proceed To Checkout']"));
		ProceedCheckout.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		WebElement poNumber = driver.findElement(By.name("PrimaryPO"));
		poNumber.sendKeys("Test_Po 6783");
		Thread.sleep(2000);
		WebElement checkBox_Check = driver.findElement(By.id("terms-conditions-agree"));
		checkBox_Check.click();
		Thread.sleep(2000);
		WebElement Proceed = driver.findElement(By.id("submit-order"));
		Proceed.click();
	}

	@Test(priority = 11, enabled = false)
	public void TruckSales() throws InterruptedException {
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
		WebElement Login_Link = wait.until(presenceOfElementLocated(By.className("icon-heart")));
		Login_Link.click();
		Thread.sleep(2000);
		WebElement TruckSales_Link = driver
				.findElement(By.xpath("//ul[@class='account-navigation list-unstyled']//a[.='Truck Sales']"));
		TruckSales_Link.click();
		Thread.sleep(2000);
		WebElement SearchTrucksLink = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchTrucksLink.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,500)");
		Thread.sleep(3000);
		WebElement OrderNo = driver.findElement(By.name("OrderNo"));
		OrderNo.sendKeys("1439964");
		Thread.sleep(2000);
		WebElement SearchWithOrderNo = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchWithOrderNo.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement Clearsearch = driver.findElement(By.xpath("//button[@type='reset']"));
		Clearsearch.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement EnterPurchaseOrder = driver.findElement(By.name("PONumber"));
		EnterPurchaseOrder.sendKeys("53428");
		Thread.sleep(2000);
		WebElement SearchwithPurchaseOrder = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchwithPurchaseOrder.click();
		Clearsearch = driver.findElement(By.xpath("//button[@type='reset']"));
		Clearsearch.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement EnterDateRangestart = driver.findElement(By.name("DateRangeStart"));
		EnterDateRangestart.sendKeys("05/08/23");
		Thread.sleep(3000);
		EnterDateRangestart.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement EnterDateRangeEnd = driver.findElement(By.name("DateRangeEnd"));
		EnterDateRangeEnd.sendKeys("05/08/23");
		Thread.sleep(3000);
		EnterDateRangeEnd.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement SearchwithDateRange = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchwithDateRange.click();
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.xpath("//button[@type='reset']"));
		Clearsearch.click();
		Thread.sleep(3000);
		WebElement EnterTruckModel = driver.findElement(By.name("TruckModel"));
		EnterTruckModel.sendKeys("E18S 36V 1346-20 Series Finished Truck");
		Thread.sleep(2000);
		WebElement SearchTruckModel = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchTruckModel.click();
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.xpath("//button[@type='reset']"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement SelectStaus = driver.findElement(By.name("OrderStatus"));
		SelectStaus.click();
		Thread.sleep(3000);
		WebElement SelectStausCompleted = driver.findElement(By.xpath("//option[.='Completed']"));
		SelectStausCompleted.click();
		Thread.sleep(3000);
		WebElement SearchwithStatus = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchwithStatus.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.xpath("//button[@type='reset']"));
		Clearsearch.click();
		OrderNo = driver.findElement(By.name("OrderNo"));
		OrderNo.sendKeys("1439964");
		Thread.sleep(2000);
		SearchWithOrderNo = driver.findElement(By.xpath("//button[text()='Search Trucks']"));
		SearchWithOrderNo.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		WebElement TruckSalesDetails = driver.findElement(By.xpath("//a[.='1439964']"));
		TruckSalesDetails.click();
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
	}

	@Test(priority = 12, enabled = false, dependsOnMethods = "login")
	public void TruckSearch() throws InterruptedException {
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
		Actions action = new Actions(driver);
		WebElement element = wait.until(presenceOfElementLocated(By.xpath("//a[.='Product Support']")));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement ClickTruckSearch = driver
				.findElement(By.xpath("//li[@class='main-navigation-level1-item']//a[.='Truck Search']"));
		ClickTruckSearch.click();
		Thread.sleep(2000);
		WebElement SearchTrucksLink = driver.findElement(By.id("searchTrucks"));
		SearchTrucksLink.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,500)");
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(3000);
		WebElement SerialNo = driver.findElement(By.name("EquipmentSearchForm_SerialNumber"));
		SerialNo.sendKeys("W4X144R01278");
		Thread.sleep(2000);
		WebElement SearchButton = driver.findElement(By.id("searchTrucks"));
		SearchButton.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement Clearsearch = driver.findElement(By.id("clearTruckSearch"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement EnterDescription = driver.findElement(By.id("EquipmentSearchForm_Description"));
		EnterDescription.sendKeys("T20S-02 Finished Truck");
		Thread.sleep(2000);
		SearchButton = driver.findElement(By.id("searchTrucks"));
		SearchButton.click();
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("clearTruckSearch"));
		Clearsearch.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		SerialNo = driver.findElement(By.name("EquipmentSearchForm_SerialNumber"));
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		SerialNo = driver.findElement(By.name("EquipmentSearchForm_SerialNumber"));
		SerialNo.sendKeys("W4X144R01278");
		Thread.sleep(2000);
		WebElement FindSerialNumber = driver.findElement(By.name("FindSerialNo"));
		FindSerialNumber.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(6000);
		WebElement History = driver.findElement(By.xpath("//a[.='History']"));
		History.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(3000);
		WebElement BacktoTruckSearch = driver
				.findElement(By.xpath("//li[@class='breadcrumbs-list']/a[.='Truck Search']"));
		BacktoTruckSearch.click();
		Thread.sleep(3000);
		Clearsearch = driver.findElement(By.id("clearTruckSearch"));
		Clearsearch.click();
		Thread.sleep(3000);
		SerialNo = driver.findElement(By.name("EquipmentSearchForm_SerialNumber"));
		SerialNo.sendKeys("W4X144R01278");
		Thread.sleep(2000);
		SearchButton = driver.findElement(By.id("searchTrucks"));
		SearchButton.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(3000);
		WebElement TruckSearchDetails = driver.findElement(
				By.xpath("/html/body/div[2]/div/div/div[3]/div/div[2]/div[3]/div[2]/div/table/tbody/tr[1]/td[2]/a"));
		TruckSearchDetails.click();
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(3000);
		WebElement InstallationReportLink = driver.findElement(By.xpath("//a[.='07/27/23']"));
		InstallationReportLink.click();
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);

	}

	@Test(priority = 13, enabled = true, dependsOnMethods = "login")
	public void TruckTransfer() throws InterruptedException {
		System.out.println("Truck Transfer Unable to test... Need to update");

	}

	@Test(priority = 14, enabled = false, dependsOnMethods = "login")
	public void InstallationReport() throws InterruptedException {
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
		Actions action = new Actions(driver);
		WebElement element = wait.until(presenceOfElementLocated(By.xpath("//a[.='Product Support']")));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement ClickTruckInstallation = driver
				.findElement(By.xpath("//li[@class='main-navigation-level1-item']//a[.='Truck Installations']"));
		ClickTruckInstallation.click();
		Thread.sleep(2000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(5000);
		js.executeScript("window.scrollBy(0,-300)");
		Thread.sleep(5000);
		WebElement StatusDropDown = driver
				.findElement(By.xpath("//select[@name='InstallationSearchForm_InstallationStatus']"));
		StatusDropDown.click();
		Thread.sleep(2000);
		WebElement SavedStatusSearch = driver.findElement(By.xpath("//option[.='Saved']"));
		SavedStatusSearch.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(5000);
		WebElement Searchreport = driver.findElement(By.xpath("//button[.='Search Reports']"));
		Searchreport.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		StatusDropDown = driver.findElement(By.xpath("//select[@name='InstallationSearchForm_InstallationStatus']"));
		StatusDropDown.click();
		Thread.sleep(3000);
		WebElement PendingStatusSearch = driver.findElement(By.xpath("//option[.='Pending']"));
		PendingStatusSearch.click();
		Thread.sleep(2000);
		Searchreport = driver.findElement(By.xpath("//button[.='Search Reports']"));
		Searchreport.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		StatusDropDown = driver.findElement(By.xpath("//select[@name='InstallationSearchForm_InstallationStatus']"));
		StatusDropDown.click();
		Thread.sleep(3000);
		WebElement ApprovedStatusSearch = driver.findElement(By.xpath("//option[.='Approved']"));
		ApprovedStatusSearch.click();
		Thread.sleep(2000);
		Searchreport = driver.findElement(By.xpath("//button[.='Search Reports']"));
		Searchreport.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement DeniedStatus = driver.findElement(By.xpath("//option[.='Denied']"));
		DeniedStatus.click();
		Thread.sleep(2000);
		Searchreport = driver.findElement(By.xpath("//button[.='Search Reports']"));
		Searchreport.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		StatusDropDown = driver.findElement(By.xpath("//select[@name='InstallationSearchForm_InstallationStatus']"));
		StatusDropDown.click();
		Thread.sleep(2000);
		WebElement SelectStatusSearch = driver.findElement(By.xpath("//option[.=' ---Select---']"));
		SelectStatusSearch.click();
		Thread.sleep(2000);
		WebElement DealerActionRequired = driver.findElement(By.xpath("//span[@class= 'txt']"));
		DealerActionRequired.click();
		Thread.sleep(2000);
		Searchreport = driver.findElement(By.xpath("//button[.='Search Reports']"));
		Searchreport.click();
		Thread.sleep(5000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement NewInstallationreport = driver.findElement(By.xpath("//a[@class= 'new-install-report mtb-20']"));
		NewInstallationreport.click();
		Thread.sleep(2000);
		WebElement formNumber = driver.findElement(By.id("InstallationCheckForm_InstallationFormNumber"));
		formNumber.sendKeys("008");
		Thread.sleep(4000);
		WebElement InternalCombution = driver
				.findElement(By.xpath("//input[@name='InstallationCheckForm_TruckType'and @value='IC']"));
		js.executeScript("arguments[0].click();", InternalCombution);
		Thread.sleep(2000);
		WebElement serialNumber = driver.findElement(By.id("InstallationCheckForm_TruckSerialNumber"));
		serialNumber.sendKeys("512048009534");
		Thread.sleep(2000);
		WebElement SubmitButton = driver.findElement(By.name("create"));
		js.executeScript("arguments[0].click();", SubmitButton);
		Thread.sleep(3000);
		WebElement Installdate = driver.findElement(By.id("InstallationForm_InstallationDate"));
		Installdate.sendKeys("05/08/23");
		Thread.sleep(3000);
		Installdate.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement InstallType = driver.findElement(By.id("option1"));
		js.executeScript("arguments[0].click();", InstallType);
		Thread.sleep(2000);
		WebElement EngineManufacturer = driver.findElement(By.name("InstallationForm_ManufacturerName"));
		EngineManufacturer.sendKeys("Test Manufacturer");
		Thread.sleep(2000);
		WebElement EngineModel = driver.findElement(By.name("InstallationForm_EngineModel"));
		EngineModel.sendKeys("Updated Test Model");
		Thread.sleep(2000);
		WebElement EngineSerialNumber = driver.findElement(By.name("InstallationForm_EngineSerialNumber"));
		EngineSerialNumber.sendKeys("T08134723094");
		Thread.sleep(2000);
		WebElement EUICustomerName = driver.findElement(By.name("InstallationForm_BusinessName"));
		EUICustomerName.sendKeys("New Customer");
		Thread.sleep(2000);
		WebElement EUIStreet = driver.findElement(By.name("InstallationForm_Street"));
		EUIStreet.sendKeys("West Avenue");
		Thread.sleep(2000);
		WebElement EUIcountyCode = driver.findElement(By.id("InstallationForm_CountyCode"));
		EUIcountyCode.sendKeys("CC678");
		Thread.sleep(2000);
		WebElement EUICity = driver.findElement(By.name("InstallationForm_City"));
		EUICity.sendKeys("NewYork");
		Thread.sleep(2000);
		WebElement EUIState = driver.findElement(By.name("InstallationForm_State"));
		EUIState.sendKeys("NewYork");
		Thread.sleep(2000);
		WebElement EUIzip = driver.findElement(By.name("InstallationForm_Zipcode"));
		EUIzip.sendKeys("8089");
		Thread.sleep(2000);
		WebElement EUISIC = driver.findElement(By.id("InstallationForm_SIC"));
		EUISIC.sendKeys("7899");
		Thread.sleep(2000);
		WebElement EUIDistance = driver.findElement(By.name("InstallationForm_DistanceFromDealer"));
		EUIDistance.clear();
		EUIDistance = driver.findElement(By.name("InstallationForm_DistanceFromDealer"));
		EUIDistance.sendKeys("20");
		Thread.sleep(2000);
		WebElement customerContactName = driver.findElement(By.name("InstallationForm_CustomerContactName"));
		customerContactName.sendKeys("Maari");
		Thread.sleep(2000);
		WebElement customerJobTitle = driver.findElement(By.name("InstallationForm_CustomerJobTitle"));
		customerJobTitle.sendKeys("Testing");
		Thread.sleep(2000);
		WebElement customerPhoneNo = driver.findElement(By.id("InstallationForm_CustomerPhoneNumber"));
		customerPhoneNo.sendKeys("929480234023");
		Thread.sleep(2000);
		WebElement customerEmail = driver.findElement(By.name("InstallationForm_CustomerEmail"));
		customerEmail.sendKeys("mar.rig10test@gmail.com");
		Thread.sleep(2000);
		WebElement SameASAbove = driver.findElement(By.name("sameOrderAddress"));
		js.executeScript("arguments[0].click();", SameASAbove);
		Thread.sleep(2000);
		WebElement Notes = driver.findElement(By.name("InstallationForm_Notes"));
		Notes.sendKeys("Test Notes");
		Thread.sleep(2000);
		WebElement Disclaimer = driver.findElement(By.name("disclaimer"));
		js.executeScript("arguments[0].click();", Disclaimer);
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		WebElement SubmitInstallation = driver.findElement(By.name("apply"));
		js.executeScript("arguments[0].click();", SubmitInstallation);
		Thread.sleep(6000);
//-------------------------------Electric type Truck Installation---------------------------------------------------
		NewInstallationreport = driver.findElement(By.xpath("//a[@class= 'new-install-report mtb-20']"));
		NewInstallationreport.click();
		Thread.sleep(2000);
		formNumber = driver.findElement(By.id("InstallationCheckForm_InstallationFormNumber"));
		formNumber.sendKeys("007");
		Thread.sleep(4000);
		WebElement Electric = driver.findElement(By.xpath("//input[@type='radio' and @value='EL']"));
		js.executeScript("arguments[0].click();", Electric);
		Thread.sleep(2000);
		WebElement serialNumberEL = driver.findElement(By.id("InstallationCheckForm_TruckSerialNumber"));
		serialNumberEL.sendKeys("710147300609");
		Thread.sleep(3000);
		WebElement ELSubmitButton = driver.findElement(By.name("create"));
		js.executeScript("arguments[0].click();", ELSubmitButton);
		Thread.sleep(3000);
		WebElement ELInstalldate = driver.findElement(By.id("InstallationForm_InstallationDate"));
		ELInstalldate.sendKeys("05/08/23");
		Thread.sleep(3000);
		ELInstalldate.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement InstallTypeEL = driver.findElement(By.id("option1"));
		js.executeScript("arguments[0].click();", InstallTypeEL);
		Thread.sleep(2000);
		WebElement EUICustomerNameEL = driver.findElement(By.name("InstallationForm_BusinessName"));
		EUICustomerNameEL.sendKeys("New Customer");
		Thread.sleep(2000);
		WebElement EUIStreetEL = driver.findElement(By.name("InstallationForm_Street"));
		EUIStreetEL.sendKeys("West Avenue");
		Thread.sleep(2000);
		WebElement EUIcountyCodeEL = driver.findElement(By.id("InstallationForm_CountyCode"));
		EUIcountyCodeEL.sendKeys("CC678");
		Thread.sleep(2000);
		WebElement EUICityEL = driver.findElement(By.name("InstallationForm_City"));
		EUICityEL.sendKeys("NewYork");
		Thread.sleep(2000);
		WebElement EUIStateEL = driver.findElement(By.name("InstallationForm_State"));
		EUIStateEL.sendKeys("NewYork");
		Thread.sleep(2000);
		WebElement EUIzipEL = driver.findElement(By.name("InstallationForm_Zipcode"));
		EUIzipEL.sendKeys("8089");
		Thread.sleep(2000);
		WebElement EUISICEL = driver.findElement(By.id("InstallationForm_SIC"));
		EUISICEL.sendKeys("7899");
		Thread.sleep(2000);
		WebElement EUIDistanceEL = driver.findElement(By.name("InstallationForm_DistanceFromDealer"));
		EUIDistanceEL.clear();
		EUIDistanceEL = driver.findElement(By.name("InstallationForm_DistanceFromDealer"));
		EUIDistanceEL.sendKeys("20");
		Thread.sleep(2000);
		WebElement customerContactNameEL = driver.findElement(By.name("InstallationForm_CustomerContactName"));
		customerContactNameEL.sendKeys("Maari");
		Thread.sleep(2000);
		WebElement customerJobTitleEL = driver.findElement(By.name("InstallationForm_CustomerJobTitle"));
		customerJobTitleEL.sendKeys("Testing");
		Thread.sleep(2000);
		WebElement customerPhoneNoEL = driver.findElement(By.id("InstallationForm_CustomerPhoneNumber"));
		customerPhoneNoEL.sendKeys("929480234023");
		Thread.sleep(2000);
		WebElement customerEmailEL = driver.findElement(By.name("InstallationForm_CustomerEmail"));
		customerEmailEL.sendKeys("mar.rig10test@gmail.com");
		Thread.sleep(2000);
		WebElement SameASAboveEL = driver.findElement(By.name("sameOrderAddress"));
		js.executeScript("arguments[0].click();", SameASAboveEL);
		Thread.sleep(2000);
		WebElement NotesEL = driver.findElement(By.name("InstallationForm_Notes"));
		NotesEL.sendKeys("Test Notes");
		Thread.sleep(2000);
		WebElement DisclaimerEL = driver.findElement(By.name("disclaimer"));
		js.executeScript("arguments[0].click();", DisclaimerEL);
		Thread.sleep(3000);
		WebElement SubmitInstallationEL = driver.findElement(By.name("apply"));
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(6000);
		js.executeScript("arguments[0].click();", SubmitInstallationEL);
		Thread.sleep(6000);
	}

	@Test(priority = 15, enabled = false, dependsOnMethods = "login")
	public void Returns() throws InterruptedException {
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
		WebElement myAccountLink = wait.until(presenceOfElementLocated(By.className("icon-heart")));
		myAccountLink.click();
		Thread.sleep(2000);
		WebElement ReturnsLink = driver.findElement(By.xpath("//ul[@class='account-navigation list-unstyled']//a[.='Returns']"));
		ReturnsLink.click();
		Thread.sleep(3000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		WebElement Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		Searchbutton.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,800)");
		Thread.sleep(3000);
		WebElement partreturnNo = driver.findElement(By.id("returnsSearchOrderNo"));
		partreturnNo.sendKeys("60055972");
		Thread.sleep(2000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		Searchbutton.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		WebElement Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,-500)");
		WebElement yourReferenceNo = driver.findElement(By.id("returnsSearchPONumber"));
		yourReferenceNo.sendKeys("45370");
		Thread.sleep(2000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		Searchbutton.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,-800)");
		WebElement EnterDateRangestart = driver.findElement(By.id("DateRangeStart"));
		EnterDateRangestart.sendKeys("05/08/23");
		Thread.sleep(3000);
		EnterDateRangestart.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement EnterDateRangeEnd = driver.findElement(By.id("DateRangeEnd"));
		EnterDateRangeEnd.sendKeys("05/08/23");
		Thread.sleep(3000);
		EnterDateRangeEnd.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		Searchbutton.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(3000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		js.executeScript("window.scrollBy(0,-500)");
		Thread.sleep(3000);
		WebElement OrderType = driver.findElement(By.name("OrderType"));
		OrderType.click();
		Thread.sleep(3000);
		WebElement SelectPartReturn= driver.findElement(By.xpath("//option[.='Part Return']"));
		SelectPartReturn.click();
		Thread.sleep(3000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(4000);
		OrderType = driver.findElement(By.name("OrderType"));
		OrderType.click();
		Thread.sleep(3000);
		WebElement SelectPartReturncredit= driver.findElement(By.xpath("//option[.='Part Return Credit']"));
		SelectPartReturncredit.click();
		Thread.sleep(3000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,1000)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		WebElement ReturnStatus = driver.findElement(By.name("OrderStatus"));
		ReturnStatus.click();
		Thread.sleep(3000);
		WebElement SelectOpen= driver.findElement(By.xpath("//option[.='Open']"));
		SelectOpen.click();
		Thread.sleep(3000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		ReturnStatus = driver.findElement(By.name("OrderStatus"));
		ReturnStatus.click();
		Thread.sleep(3000);
		WebElement SelectCompleted= driver.findElement(By.xpath("//option[.='Completed']"));
		SelectCompleted.click();
		Thread.sleep(3000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		WebElement partNo = driver.findElement(By.name("ProductIdentifier_1"));
		partNo.sendKeys("13131084003");
		Thread.sleep(2000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("returnsSearchClear"));
		Clearsearch.click();
		Thread.sleep(3000);
		partreturnNo = driver.findElement(By.id("returnsSearchOrderNo"));
		partreturnNo.sendKeys("60055972");
		Thread.sleep(2000);
		Searchbutton= driver.findElement(By.xpath("//button[.='Search Returns']"));
		js.executeScript("arguments[0].click();", Searchbutton);	
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		WebElement ReturnsDetails = driver.findElement(By.xpath("//a[.='60055972']"));
		js.executeScript("arguments[0].click();", ReturnsDetails);
		js.executeScript("window.scrollBy(0,500)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-500)", "driver");
		Thread.sleep(6000);
		WebElement backReturns=driver.findElement(By.xpath("//li[@class='breadcrumbs-list']//a[.='Returns']"));
		backReturns.click();
		Thread.sleep(2000);
		WebElement NewReturnRequest= driver.findElement(By.xpath("//div[@class='row']//a[.='New Return Request']"));
		NewReturnRequest.click();
		Thread.sleep(2000);
		WebElement invoiceNumber= driver.findElement(By.name("InvoiceNo"));
		invoiceNumber.sendKeys("91325609");
		Thread.sleep(4000);
		WebElement ProceedButton = driver.findElement(By.xpath("//button[.='Proceed']"));
		ProceedButton.click();
		Thread.sleep(3000);
		WebElement ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		ChangeReason.click();
		Thread.sleep(3000);
		WebElement priceBillingError = driver.findElement(By.id("option1"));
		js.executeScript("arguments[0].click();", priceBillingError);
		Thread.sleep(3000);
		WebElement SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement dealerOrderInError = driver.findElement(By.id("option2"));
		js.executeScript("arguments[0].click();", dealerOrderInError);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement IncorrectlySpecified = driver.findElement(By.id("option3"));
		js.executeScript("arguments[0].click();", IncorrectlySpecified);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement documentManualIncorrect = driver.findElement(By.id("option4"));
		js.executeScript("arguments[0].click();", documentManualIncorrect);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement ShortShipped = driver.findElement(By.id("option5"));
		js.executeScript("arguments[0].click();", ShortShipped);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement duplicateShipment = driver.findElement(By.id("option6"));
		js.executeScript("arguments[0].click();", duplicateShipment);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement mismarkedInventory = driver.findElement(By.id("option7"));
		js.executeScript("arguments[0].click();", mismarkedInventory);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement damagedInTransitbyCarrier = driver.findElement(By.id("option8"));
		js.executeScript("arguments[0].click();", damagedInTransitbyCarrier);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement damagedInTransitBOPackaging = driver.findElement(By.id("option9"));
		js.executeScript("arguments[0].click();", damagedInTransitBOPackaging);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement lostInTransit = driver.findElement(By.id("option10"));
		js.executeScript("arguments[0].click();", lostInTransit);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement freightOverCharge = driver.findElement(By.id("option11"));
		js.executeScript("arguments[0].click();", freightOverCharge);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement freightForReOrder = driver.findElement(By.id("option12"));
		js.executeScript("arguments[0].click();", freightForReOrder);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement freightForreturn = driver.findElement(By.id("option13"));
		js.executeScript("arguments[0].click();", freightForreturn);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		ChangeReason = driver.findElement(By.xpath("//a[.='Change Reason']"));
		js.executeScript("arguments[0].click();", ChangeReason);
		Thread.sleep(3000);
		WebElement CoreExchange = driver.findElement(By.id("option14"));
		js.executeScript("arguments[0].click();", CoreExchange);
		Thread.sleep(3000);
		SelectReason = driver.findElement(By.id("selectreason"));
		SelectReason.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
		Thread.sleep(6000);
		backReturns=driver.findElement(By.xpath("//li[@class='breadcrumbs-list']//a[.='Returns']"));
		backReturns.click();
		Thread.sleep(2000);
		NewReturnRequest= driver.findElement(By.xpath("//div[@class='row']//a[.='New Return Request']"));
		NewReturnRequest.click();
		Thread.sleep(2000);
		invoiceNumber= driver.findElement(By.name("InvoiceNo"));
		invoiceNumber.sendKeys("91433684");
		Thread.sleep(4000);
		ProceedButton = driver.findElement(By.xpath("//button[.='Proceed']"));
		ProceedButton.click();
		Thread.sleep(3000);
		WebElement Notes= driver.findElement(By.name("ReturnReasonText"));
		Notes.sendKeys("Test Return");
		Thread.sleep(4000);
		WebElement Email= driver.findElement(By.id("returnemailid"));
		Email.sendKeys("marig10test@gmail.com");
		Thread.sleep(4000);
		WebElement product1= driver.findElement(By.name("Qty_1"));
		product1.clear();
		product1= driver.findElement(By.name("Qty_1"));
		product1.sendKeys("1");
		Thread.sleep(4000);
		WebElement product2= driver.findElement(By.name("Qty_2"));
		product2.clear();
		product2= driver.findElement(By.name("Qty_2"));
		product2.sendKeys("1");
		Thread.sleep(4000);
		WebElement product3= driver.findElement(By.name("Qty_4"));
		product3.clear();
		driver.findElement(By.name("Qty_4"));
		product3.sendKeys("1");
		Thread.sleep(4000);
		WebElement updateButton = driver.findElement(By.name("Update"));
		updateButton.click();
		Thread.sleep(4000);
		WebElement Proceed = driver.findElement(By.name("Confirm"));
		Proceed.click();
		Thread.sleep(4000);
		WebElement submitReturn = driver.findElement(By.name("Submit"));
		submitReturn.click();
		Thread.sleep(4000);
		js.executeScript("window.scrollBy(0,800)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-1000)");
	}

	@Test(priority=16, enabled=true)
	public void WarrantyManagement() throws InterruptedException
	{
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
		Actions action = new Actions(driver);
		WebElement element = wait.until(presenceOfElementLocated(By.xpath("//a[.='Product Support']")));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement WarrantyManagementLink = driver.findElement(By.xpath("//li[@class='main-navigation-level1-item']//a[.='Warranty Management']"));
		WarrantyManagementLink.click();
		Thread.sleep(4000);
		WebElement ClaimSort=driver.findElement(By.id("claimnumber_col"));
		ClaimSort.click();
		Thread.sleep(6000);
		ClaimSort=driver.findElement(By.id("claimnumber_col"));
		ClaimSort.click();
		Thread.sleep(6000);
		WebElement submitDateSort=driver.findElement(By.id("submitteddate_col"));
		submitDateSort.click();
		Thread.sleep(6000);
		submitDateSort=driver.findElement(By.id("submitteddate_col"));
		submitDateSort.click();
		Thread.sleep(6000);
		WebElement workOrderSort=driver.findElement(By.id("workorder_col"));
		workOrderSort.click();
		Thread.sleep(6000);
		workOrderSort=driver.findElement(By.id("workorder_col"));
		workOrderSort.click();
		Thread.sleep(6000);
		WebElement SerialNoSort=driver.findElement(By.id("serialnumber_col"));
		SerialNoSort.click();
		Thread.sleep(6000);
		SerialNoSort=driver.findElement(By.id("serialnumber_col"));
		SerialNoSort.click();
		Thread.sleep(6000);
		WebElement claimTypeSort=driver.findElement(By.id("claimtype_col"));
		claimTypeSort.click();
		Thread.sleep(6000);
		claimTypeSort=driver.findElement(By.id("claimtype_col"));
		claimTypeSort.click();
		Thread.sleep(6000);
		WebElement dueDateSort=driver.findElement(By.id("duedate_col"));
		dueDateSort.click();
		Thread.sleep(6000);
		dueDateSort=driver.findElement(By.id("duedate_col"));
		dueDateSort.click();
		Thread.sleep(6000);
		WebElement customer_colStart=driver.findElement(By.id("customer_col"));
		customer_colStart.click();
		Thread.sleep(6000);
		customer_colStart=driver.findElement(By.id("customer_col"));
		customer_colStart.click();
		Thread.sleep(6000);
		WebElement ClaimStatusSort=driver.findElement(By.id("claimstatus_col"));
		ClaimStatusSort.click();
		Thread.sleep(6000);
		ClaimStatusSort=driver.findElement(By.id("claimstatus_col"));
		ClaimStatusSort.click();
		Thread.sleep(6000);
		WebElement ClaimAmountSort=driver.findElement(By.id("claimamount_col"));
		ClaimAmountSort.click();
		Thread.sleep(6000);
		ClaimAmountSort=driver.findElement(By.id("claimamount_col"));
		ClaimAmountSort.click();
		Thread.sleep(6000);
		WebElement approvalamount_col=driver.findElement(By.id("approvalamount_col"));
		approvalamount_col.click();
		Thread.sleep(6000);
		approvalamount_col=driver.findElement(By.id("approvalamount_col"));
		approvalamount_col.click();
		Thread.sleep(6000);
		WebElement ApproveDate=driver.findElement(By.id("approveddate_col"));
		ApproveDate.click();
		Thread.sleep(6000);
		ApproveDate=driver.findElement(By.id("approveddate_col"));
		ApproveDate.click();
		Thread.sleep(3000);
		JavascriptExecutor js = (JavascriptExecutor) driver;
		WebElement ClaimNoSearch=driver.findElement(By.name("Warranty_ClaimNumber"));
		ClaimNoSearch.sendKeys("7425388");
		Thread.sleep(2000);
		WebElement SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		WebElement Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement workOrder=driver.findElement(By.name("Warranty_WorkOrder"));
		workOrder.sendKeys("1234");
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		WebElement SubmitDatestart=driver.findElement(By.id("submittedDateStart"));
		SubmitDatestart.sendKeys("07/06/23");
		Thread.sleep(2000);
		SubmitDatestart=driver.findElement(By.id("submittedDateStart"));
		SubmitDatestart.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement SubmitDateEnd=driver.findElement(By.id("submittedDateEnd"));
		SubmitDateEnd.sendKeys("07/13/23");
		Thread.sleep(2000);
		SubmitDateEnd=driver.findElement(By.id("submittedDateEnd"));
		SubmitDateEnd.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement partNo=driver.findElement(By.name("Warranty_PartNumber"));
		partNo.sendKeys("L1854460174");
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement TKSerialNo=driver.findElement(By.name("Warranty_SerialNumber"));
		TKSerialNo.sendKeys("W4X360Z01430");
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement ApproveDatestart=driver.findElement(By.id("approvalDateStart"));
		ApproveDatestart.sendKeys("07/06/23");
		Thread.sleep(2000);
		ApproveDatestart=driver.findElement(By.id("approvalDateStart"));
		ApproveDatestart.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		WebElement ApproveDateEnd=driver.findElement(By.id("approvalDateEnd"));
		ApproveDateEnd.sendKeys("07/13/23");
		Thread.sleep(2000);
		ApproveDateEnd=driver.findElement(By.id("approvalDateEnd"));
		ApproveDateEnd.sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement claimStatus = driver.findElement(By.name("Warranty_ClaimStatus"));
		claimStatus.click();
		Thread.sleep(3000);
		WebElement SelectSaved= driver.findElement(By.xpath("//option[.='Saved Claims']"));
		SelectSaved.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(3000);
		claimStatus = driver.findElement(By.name("Warranty_ClaimStatus"));
		claimStatus.click();
		Thread.sleep(2000);
		WebElement SelectSubmitted= driver.findElement(By.xpath("//option[.='Submitted Claims']"));
		SelectSubmitted.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		claimStatus = driver.findElement(By.name("Warranty_ClaimStatus"));
		claimStatus.click();
		Thread.sleep(2000);
		WebElement SelectProcessed= driver.findElement(By.xpath("//option[.='Processed Claims']"));
		SelectProcessed.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement ClaimType = driver.findElement(By.name("Warranty_ClaimType"));
		ClaimType.click();
		Thread.sleep(2000);
		WebElement SelectTruck= driver.findElement(By.xpath("//option[.='Truck']"));
		SelectTruck.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		ClaimType = driver.findElement(By.name("Warranty_ClaimType"));
		ClaimType.click();
		Thread.sleep(2000);
		WebElement SelectPart= driver.findElement(By.xpath("//option[.='Part']"));
		SelectPart.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		ClaimType = driver.findElement(By.name("Warranty_ClaimType"));
		ClaimType.click();
		Thread.sleep(2000);
		WebElement Selectfreight= driver.findElement(By.xpath("//option[.='Freight']"));
		Selectfreight.click();
		Thread.sleep(3000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(2000);
		WebElement dealerActionRequired = driver.findElement(By.xpath("//span[.='Dealer Action Required']"));
		dealerActionRequired.click();
		Thread.sleep(2000);
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		WebElement newMessage = driver.findElement(By.xpath("//span[.='New Messages']"));
		newMessage.click();
		SearchClaim=driver.findElement(By.name("searchClaims"));
		SearchClaim.click();
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,300)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		Clearsearch = driver.findElement(By.id("warranty-clear-search"));
		Clearsearch.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,-800)");
		WebElement truckClaim= driver.findElement(By.xpath("//a[.='Click here to create a new claim']"));
		truckClaim.click();
		Thread.sleep(2000);
		WebElement EnterTruckSerial= driver.findElement(By.id("equipmentserial"));
		EnterTruckSerial.sendKeys("W4X360Z01419");
		Thread.sleep(2000);
		WebElement submitClaim= driver.findElement(By.id("type-select-submit"));
		submitClaim.click();
		Thread.sleep(2000);
		WebElement EnterWorkOrder= driver.findElement(By.name("WorkOrder"));
		EnterWorkOrder.sendKeys("Test Work Order");
		Thread.sleep(2000);
		WebElement failureDate= driver.findElement(By.id("FailureDate"));
		failureDate.sendKeys("08/17/2023");
		Thread.sleep(2000);
		WebElement causingFailure= driver.findElement(By.id("PartCausingFailure"));
		causingFailure.sendKeys("Facing Starting trouble");
		Thread.sleep(2000);
		WebElement RepaireDate= driver.findElement(By.id("RepairDate"));
		RepaireDate.sendKeys("08/18/2023");
		Thread.sleep(2000);
		WebElement hourMeter= driver.findElement(By.id("HourMeter"));
		hourMeter.sendKeys("8");
		Thread.sleep(2000);
		WebElement Notes= driver.findElement(By.name("Notes"));
		Notes.sendKeys("Testing team claim");
		Thread.sleep(2000);
		WebElement proceedclaim= driver.findElement(By.name("proceed"));
		proceedclaim.click();
		Thread.sleep(3000);
		WebElement AddLindeParts= driver.findElement(By.id("addlindeparts"));
		AddLindeParts.click();
		Thread.sleep(3000);
		WebElement Claimproduct1= driver.findElement(By.id("warranty-addlindeitem-sku_1"));
		Claimproduct1.sendKeys("1864460021");
		Thread.sleep(3000);
		Claimproduct1= driver.findElement(By.id("warranty-addlindeitem-sku_1"));
		Claimproduct1.sendKeys(Keys.ENTER);
		Thread.sleep(3000);
		WebElement Claimproduct2= driver.findElement(By.id("warranty-addlindeitem-sku_2"));
		Claimproduct2.sendKeys("1164453351");
		Thread.sleep(3000);
		Claimproduct2= driver.findElement(By.id("warranty-addlindeitem-sku_2"));
		Claimproduct2.sendKeys(Keys.ENTER);
		Thread.sleep(3000);
		WebElement AddItems= driver.findElement(By.id("add-line-item"));
		AddItems.click();
		Thread.sleep(3000);
		WebElement BacktoClaim= driver.findElement(By.xpath("//a[.='Back To Claim']"));
		BacktoClaim.click();
		Thread.sleep(3000);
		js.executeScript("window.scrollBy(0,400)", "driver");
		Thread.sleep(6000);
		js.executeScript("window.scrollBy(0,-800)");
		Thread.sleep(6000);
		WebElement AddNonLindeParts= driver.findElement(By.id("addnonlindeparts"));
		AddNonLindeParts.click();
		Thread.sleep(3000);
		WebElement AddPartstoNONLinde= driver.findElement(By.name("QuantityValue_1"));
		AddPartstoNONLinde.sendKeys("10");
		Thread.sleep(3000);
		WebElement AddDescription= driver.findElement(By.name("Description_1"));
		AddDescription.sendKeys("Barring Wheel");
		Thread.sleep(3000);
		WebElement Addprice= driver.findElement(By.name("UnitPriceValue_1"));
		Addprice.sendKeys("100");
		Thread.sleep(3000);
		WebElement AddLineItems= driver.findElement(By.id("add-line-item"));
		AddLineItems.sendKeys("100");
		Thread.sleep(3000);
		BacktoClaim= driver.findElement(By.xpath("//a[.='Back To Claim']"));
		BacktoClaim.click();
		Thread.sleep(3000);
		WebElement AddMissellionsItems= driver.findElement(By.id("addMiscellaneousItems"));
		AddMissellionsItems.click();
		Thread.sleep(3000);
		WebElement AddMissellionsLineItems= driver.findElement(By.name("Description_1"));
		AddMissellionsLineItems.sendKeys("Test product");
		Thread.sleep(3000);
		WebElement AddMissellionsCharge= driver.findElement(By.name("UnitPriceValue_1"));
		AddMissellionsCharge.sendKeys("50");
		Thread.sleep(3000);
		AddLineItems= driver.findElement(By.id("add-line-item"));
		AddLineItems.click();
		Thread.sleep(3000);
		BacktoClaim= driver.findElement(By.xpath("//a[.='Back To Claim']"));
		BacktoClaim.click();
		Thread.sleep(3000);
		WebElement EditLaborItems= driver.findElement(By.id("addLabourItems"));
		EditLaborItems.click();
		Thread.sleep(3000);
		WebElement LabourHours= driver.findElement(By.name("Shoplabor"));
		LabourHours.clear();
		Thread.sleep(3000);
		LabourHours= driver.findElement(By.name("Shoplabor"));
		LabourHours.sendKeys("50");
		Thread.sleep(3000);
		LabourHours= driver.findElement(By.name("Shoplabor"));
		LabourHours.sendKeys(Keys.ENTER);
		Thread.sleep(3000);
		WebElement AddLabourIems= driver.findElement(By.id("edit-labor-btn"));
		AddLabourIems.click();
		Thread.sleep(3000);
		BacktoClaim= driver.findElement(By.xpath("//a[.='Back To Claim']"));
		BacktoClaim.click();
		Thread.sleep(3000);
		WebElement Calculate= driver.findElement(By.id("simulate-warranty"));
		Calculate.click();
		Thread.sleep(3000);
		WebElement Submit= driver.findElement(By.name("submitClaim"));
		Submit.click();
		Thread.sleep(3000);
		element = wait.until(presenceOfElementLocated(By.xpath("//a[.='Product Support']")));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WebElement WarrantyManagent2 = driver.findElement(By.xpath("//li[@class='main-navigation-level1-item']//a[.='Warranty Management']"));
		WarrantyManagent2.click();
		Thread.sleep(3000);
		truckClaim= driver.findElement(By.xpath("//a[.='Click here to create a new claim']"));
		truckClaim.click();
		Thread.sleep(2000);
		WebElement PartClaim = driver.findElement(By.id("ClaimTypeSelectBox"));
		PartClaim.click();
		Thread.sleep(3000);
		WebElement SelectPartClaim= driver.findElement(By.xpath("//option[.='Parts Claim']"));
		SelectPartClaim.click();
		Thread.sleep(2000);
		submitClaim= driver.findElement(By.id("type-select-submit"));
		submitClaim.click();
		Thread.sleep(2000);
		EnterWorkOrder= driver.findElement(By.name("WorkOrder"));
		EnterWorkOrder.sendKeys("Test Work Order");
		Thread.sleep(2000);
		WebElement InstallDate= driver.findElement(By.id("InstallDate"));
		InstallDate.sendKeys("08/17/2023");
		Thread.sleep(2000);
		causingFailure= driver.findElement(By.id("PartCausingFailure"));
		causingFailure.sendKeys("Facing Starting trouble");
		Thread.sleep(2000);
		WebElement FailureDate= driver.findElement(By.id("FailureDate"));
		FailureDate.sendKeys("08/18/2023");
		Thread.sleep(3000);
		Notes= driver.findElement(By.name("Notes"));
		Notes.sendKeys("Testing team claim");
		Thread.sleep(2000);
		proceedclaim= driver.findElement(By.name("proceed"));
		proceedclaim.click();
		Thread.sleep(3000);
		WebElement Addpartsclaim= driver.findElement(By.id("add-line-item"));
		Addpartsclaim.click();
		Thread.sleep(3000);
		Claimproduct1= driver.findElement(By.id("warranty-addlindeitem-sku_1"));
		Claimproduct1.sendKeys("1864460021");
		Thread.sleep(3000);
		Claimproduct1= driver.findElement(By.id("warranty-addlindeitem-sku_1"));
		Claimproduct1.sendKeys(Keys.ENTER);
		Thread.sleep(3000);
		Claimproduct2= driver.findElement(By.id("warranty-addlindeitem-sku_2"));
		Claimproduct2.sendKeys("1164453351");
		Thread.sleep(3000);
		Claimproduct2= driver.findElement(By.id("warranty-addlindeitem-sku_2"));
		Claimproduct2.sendKeys(Keys.ENTER);
		Thread.sleep(3000);
		AddItems= driver.findElement(By.id("add-line-item"));
		AddItems.click();
		Thread.sleep(3000);
		BacktoClaim= driver.findElement(By.xpath("//a[.='Back To Claim']"));
		BacktoClaim.click();
		Thread.sleep(3000);
		Calculate= driver.findElement(By.id("simulate-warranty"));
		Calculate.click();
		Thread.sleep(3000);
	    Submit= driver.findElement(By.name("submitClaim"));
		Submit.click();
		Thread.sleep(3000);
		element = wait.until(presenceOfElementLocated(By.xpath("//a[.='Product Support']")));
		action.moveToElement(element).perform();
		Thread.sleep(2000);
		WarrantyManagementLink = driver.findElement(By.xpath("//li[@class='main-navigation-level1-item']//a[.='Warranty Management']"));
		WarrantyManagementLink.click();
		Thread.sleep(3000);
		truckClaim= driver.findElement(By.xpath("//a[.='Click here to create a new claim']"));
		truckClaim.click();
		Thread.sleep(3000);
		WebElement FreightClaim = driver.findElement(By.id("ClaimTypeSelectBox"));
		FreightClaim.click();
		Thread.sleep(3000);
		WebElement SelectFreightClaim= driver.findElement(By.xpath("//option[.='Freight Claim']"));
		SelectFreightClaim.click();
		Thread.sleep(3000);
		WebElement Submit1= driver.findElement(By.id("type-select-submit"));
		Submit1.click();
		Thread.sleep(3000);
		Notes= driver.findElement(By.name("Notes"));
		Notes.sendKeys("Testing team claim");
		Thread.sleep(2000);
		WebElement FreightValue= driver.findElement(By.name("FreightValue"));
		FreightValue.sendKeys("700");
		Thread.sleep(3000);
		proceedclaim= driver.findElement(By.name("proceed"));
		proceedclaim.click();
		Thread.sleep(3000);
		Calculate= driver.findElement(By.id("simulate-warranty"));
		Calculate.click();
		Thread.sleep(3000);
	    Submit= driver.findElement(By.name("submitClaim"));
		Submit.click();
		Thread.sleep(3000);
	
	}
	@BeforeMethod(enabled = false)
	public void beforeMethod() throws InterruptedException {
		WebElement Login_Link = driver.findElement(By.className("icon-heart"));
		Login_Link.click();
		Thread.sleep(2000);
		WebElement email = driver.findElement(By.xpath("//input[@placeholder='Emailaddress']"));
		email.sendKeys("mar.ig10test@gmail.com");
		Thread.sleep(2000);
		WebElement password = driver.findElement(By.xpath("//input[@placeholder='Password']"));
		password.sendKeys("Test@123");
		Thread.sleep(2000);
		WebElement loginButton = driver.findElement(By.xpath("//button[.='Login']"));
		loginButton.click();
		Thread.sleep(2000);
		WebElement Dealer_Selection = driver
				.findElement(By.xpath("/html/body/div[2]/div/div/div[2]/div[2]/div[3]/div[1]"));
		Dealer_Selection.click();
		Thread.sleep(2000);
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		WebElement SelectAll = driver.findElement(By.id("selectAllItem"));
		SelectAll.click();
		Thread.sleep(2000);
		if (driver.findElement(By.id("deleteItems")).isEnabled())
			driver.findElement(By.id("deleteItems"));
		Thread.sleep(2000);
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(3000);
	}

	@AfterMethod(enabled = false)
	public void afterMethod() throws InterruptedException {
		WebElement availabilityPricing = driver
				.findElement(By.xpath("//li[@class='dropdown']/a[.='Availability & Pricing']"));
		availabilityPricing.click();
		Thread.sleep(2000);
		WebElement SelectAll = driver.findElement(By.id("selectAllItem"));
		SelectAll.click();
		Thread.sleep(2000);
		if (driver.findElement(By.id("deleteItems")).isEnabled())
			driver.findElement(By.id("deleteItems"));
		WebElement Home = driver.findElement(By.xpath("//a[@rel='home']/img[@title='Kion Logo']"));
		Home.click();
		Thread.sleep(2000);
	}

	@SuppressWarnings("deprecation")
	@BeforeClass
	public void beforeClass() {
		System.setProperty("webdriver.chrome.driver", "D:\\Automation setup\\chromedriver-win64\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.get("https://tst.lindelink.com/");
	}

	@AfterClass
	public void afterClass() {
	}

	@BeforeTest
	public void beforeTest() {
	}

	@AfterTest
	public void afterTest() {
	}

	@BeforeSuite
	public void beforeSuite() {
	}

	@AfterSuite
	public void afterSuite() {
	}

}
